apiVersion: apps/v1
kind: Deployment
metadata:
  name: remstrava-front
spec:
  replicas: 1
  selector:
    matchLabels:
      app: remstrava-front
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5 
  template:
    metadata:
      labels:
        app: remstrava-front
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
      - name: remstrava-front-end
        image: remstrava.azurecr.io/remstrava/frontend/1:latest
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 250m
          limits:
            cpu: 500m
---
apiVersion: v1
kind: Service
metadata:
    annotations:
        service.beta.kubernetes.io/azure-dns-label-name: remstrava
    name: remstrava-frontend
spec:
    type: LoadBalancer
    ports:
    - port: 80
    selector:
        app: remstrava-front